import { Inter } from "next/font/google";
import styles from "./page.module.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <main className={styles.main}>
          <article className={styles.article}>
            <h1 className={styles.h1}>eToken Claim Site!</h1>
            <div>
              <p className={styles.p}>
                Aquí tu puedes reclamar: tal etoken
              </p>
              {/* <p className={styles.p}>
                Reclamos hasta ahora: 
              </p> */}
              <p className={styles.p}>
                Estado de faucet: activo o inactivo
              </p>

              <p className={styles.p}>
                {children}
              </p>
            </div>
          </article>
        
        
        </main>
        
      </body>
    </html>
  );
}
