'use client'

import { useState, useEffect } from "react";
import { Inter } from "next/font/google";
import styles from "./page.module.css";
import "./globals.css";
import {toast} from "react-toastify"

import { getEtokenInfo } from "./api/getEtokenInfo/getEtokenInfo";
import { shortenText } from "./utils/shortenText";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}) 
  {
    const [availableTokens, setAvailableTokens] = useState("")
    const [tokenId, setTokenId] = useState("")
    const [shortenedTokenId, setShortenedTokenId] = useState("")
    useEffect(()=>{
      getEtokenInfo()
        .then(res => {
          if(res.error === false){
              console.log(res)
              setAvailableTokens(res.data.availableTokens)
              const shortenedText = shortenText(res.data.tokenId)
              setTokenId(res.data.tokenId)
              setShortenedTokenId(shortenedText)
              return
          }
          toast.error(res.message)
          return
        })
        .catch((err) => {
            toast.error(err.toString())
        })
    },[])
  return (
    <html lang="en">
      <body className={inter.className}>

        <main className={styles.main}>
          <article className={styles.article}>
            <h1 className={styles.h1}>eToken Claim Site!</h1>
            <div>
              <p className={styles.p} title={tokenId}>
                Aquí tu puedes reclamar: {shortenedTokenId}
              </p>
              {/* <p className={styles.p}>
                Reclamos hasta ahora: 
              </p> */}
              <p className={styles.p}>
                Etokens disponibles: {availableTokens}
              </p>

              <p className={styles.p}>
                {children}
              </p>
            </div>
          </article>
        
        
        </main>
        
      </body>
    </html>
  );
}
